import type {MultiplayerBridge} from './bridge';
import {setupMemoryView,type MemoryEntry} from './memory-view';
import {consumables,itemLabel,playerInventory,type ItemName} from '../player-inventory';
import {ensureCollectible,itemIcon} from '../collectible-art';
import {registerGachaTextures} from '../gacha-assets';
import {registerProductTextures} from '../product-textures';
import {dockPrompt} from '../hud';

type Entry=MemoryEntry;
type Slot={name:string;count:number;seasoning:string[]}|null;
type Offer={id:string;sender:string;recipient:string;kind:string;item:string;status:string;expires:number;fromRole:string;toRole:string};
export function setupLifeUI(bridge:MultiplayerBridge,request:(path:string,input?:any)=>Promise<any>,publish:()=>Promise<void>,client:string,notice:(s:string)=>void){
 const root=document.createElement('div');root.id='life-ui';root.innerHTML=`<dialog id="journal-dialog" class="social-dialog memory-dialog"></dialog><dialog id="bag-dialog" class="social-dialog"><div class="panel-heading"><h2>随身物品</h2><button data-close-life>关闭</button></div><p id="bag-hand"></p><div class="bag-tabs"><button id="bag-tab" aria-pressed="true">背包 · 四格</button><button id="collection-tab" aria-pressed="false">收藏</button></div><div id="bag-slots"></div><div id="collection-slots" hidden></div><p id="collection-help" hidden>点击收藏的物件，拿回手里。</p><div class="settings-actions"><button id="bag-stow">收进背包</button><button id="bag-consume">吃 / 喝</button><button id="bag-collect">收进收藏</button></div></dialog><section id="hand-actions" hidden aria-label="手中物品"><span id="hand-item"></span><button id="hand-use"></button></section><section id="life-offers" class="social-panel" aria-live="polite" hidden></section>`;
 document.querySelector('.world')!.append(root);
 // dockPrompt moves #hand-actions to #hud-rail, so keep direct references instead of re-querying root.
 const quick=root.querySelector<HTMLElement>('#hand-actions'),handLabel=root.querySelector<HTMLElement>('#hand-item'),handUse=root.querySelector<HTMLButtonElement>('#hand-use');
 dockPrompt(quick);
 const tools=document.getElementById('game-tools')!;
 let bag:Slot[]=[null,null,null,null],collection:Slot[]=[],collectionOpen=false,offers:Offer[]=[],entries:Entry[]=[],owner='',signature='',clockOffset=0,loading=false,loadingJournal=false;
 let bagSignature='';
 const button=(text:string,action:()=>void)=>{const b=document.createElement('button');b.textContent=text;b.onclick=action;return b;};
 const journalDialog=root.querySelector<HTMLDialogElement>('#journal-dialog')!,bagDialog=root.querySelector<HTMLDialogElement>('#bag-dialog')!;
 const memories=setupMemoryView(journalDialog,bridge);
 root.querySelectorAll('[data-close-life]').forEach(b=>b.addEventListener('click',()=>{(b.closest('dialog') as HTMLDialogElement).close();document.querySelector<HTMLElement>('.world')!.focus();}));
 async function journal(more=false){if(!bridge.user?.role){notice('登录后查看自己的经历');return;}if(loadingJournal)return;loadingJournal=true;try{const result=await request('journal'+(more&&entries.length?'?before='+entries[entries.length-1].seq:''));entries=more?[...entries,...result.entries]:result.entries;memories.set(entries,more);const moreButton=journalDialog.querySelector<HTMLButtonElement>('#journal-more');if(moreButton)moreButton.hidden=result.entries.length<50;if(!journalDialog.open)journalDialog.showModal();}catch(e){notice((e as Error).message);}finally{loadingJournal=false;}}
 function icon(element:HTMLElement,name:string){const scene=bridge.active;if(!scene)return;registerProductTextures(scene);registerGachaTextures(scene);const put=()=>{const src=itemIcon(scene,name);if(src&&element.isConnected){const img=document.createElement('img');img.src=src;img.alt='';element.prepend(img);}};if(name.startsWith('拼豆·'))void ensureCollectible(scene,name).then(put).catch(()=>{});else put();}
 function drawBag(){const next=JSON.stringify([bridge.user?.id,bridge.user?.hand,bag,collection,loading,bridge.active?.sys.settings.key,!!document.querySelector('#arcade-game[open],#perler-workshop[open]')]);if(next===bagSignature)return;bagSignature=next;const hand=bridge.user?.hand,edible=!!hand&&consumables.includes(hand),collectible=!!hand&&!edible&&hand!=='碗筷';root.querySelector('#bag-hand')!.textContent='手里：'+(hand?itemLabel(hand):'空');
  const drawSlots=(id:string,entries:Slot[],action:string)=>{const slots=root.querySelector(id)!;slots.replaceChildren();entries.forEach((s,i)=>{const b=button(s?`${itemLabel(s.name)} × ${s.count}`:'空格',()=>void inventory(action,i));b.disabled=!s||!!hand||loading;slots.append(b);if(s)icon(b,s.name);});if(!entries.length)slots.textContent='还没有收藏。拼好的豆豆、抓到的娃娃和扭蛋，都能收进来。';};drawSlots('#bag-slots',bag,'equip');drawSlots('#collection-slots',collection,'retrieve');
  (root.querySelector('#bag-stow') as HTMLButtonElement).disabled=!hand||loading;(root.querySelector('#bag-consume') as HTMLButtonElement).disabled=!edible||loading;(root.querySelector('#bag-collect') as HTMLButtonElement).disabled=!collectible||loading;
  if(quick)quick.hidden=!(edible||collectible)||!!document.querySelector('#arcade-game[open],#perler-workshop[open]');if(handLabel){handLabel.replaceChildren();handLabel.textContent=hand?itemLabel(hand):'';if(hand)icon(handLabel,hand);}if(handUse){handUse.textContent=edible?['咖啡','可乐','气泡水','冰红茶','水'].includes(hand!)?'喝掉':'吃掉':'收藏';handUse.disabled=loading;}
  (root.querySelector('#collection-tab') as HTMLButtonElement).textContent='收藏 · '+collection.reduce((n,s)=>n+(s?.count??0),0);
 }
 async function inventory(action:string,slot?:number){if(loading)return;loading=true;drawBag();const hand=bridge.user?.hand;try{await publish();const input={action,slot,client,revision:bridge.user?.revision,requestId:crypto.randomUUID()};let result;try{result=await request('inventory',input);}catch(e){if((e as any).status)throw e;result=await request('inventory',input);}bridge.user=result.self;playerInventory.hand=result.self.hand as ItemName|null;playerInventory.noodleSeasoning=result.self.seasoning??[];const ui=document.getElementById('social-ui');if(ui)ui.dataset.revision=String(result.self.revision);bag=result.bag;collection=result.collection??collection;window.dispatchEvent(new Event('hutong:hand-changed'));if(action==='consume')notice(`享用了${hand}。`);if(action==='collect')notice('已收进收藏，随时可以拿回。');}catch(e){notice((e as Error).message);}finally{loading=false;drawBag();}}
 function tab(collect:boolean){collectionOpen=collect;for(const [id,hidden]of [['#bag-slots',collect],['#collection-slots',!collect],['#collection-help',!collect]] as const)(root.querySelector(id) as HTMLElement).hidden=hidden;root.querySelector('#bag-tab')!.setAttribute('aria-pressed',String(!collect));root.querySelector('#collection-tab')!.setAttribute('aria-pressed',String(collect));}
 root.querySelector('#bag-tab')!.addEventListener('click',()=>tab(false));root.querySelector('#collection-tab')!.addEventListener('click',()=>tab(true));
 journalDialog.querySelector('#journal-more')?.addEventListener('click',()=>void journal(true));
 root.querySelector('#bag-stow')!.addEventListener('click',()=>void inventory('stow'));
 root.querySelector('#bag-consume')!.addEventListener('click',()=>void inventory('consume'));
 root.querySelector('#bag-collect')!.addEventListener('click',()=>void inventory('collect'));
 handUse?.addEventListener('click',()=>void inventory(consumables.includes(bridge.user?.hand??'')?'consume':'collect'));
 const openBag=async()=>{if(!bridge.user?.role){notice('登录后打开背包');return;}try{const result=await request('life');bag=result.bag;collection=result.collection??[];tab(collectionOpen);drawBag();bagDialog.showModal();}catch(e){notice((e as Error).message);}};
 const openCollection=()=>{tab(true);void openBag();};window.addEventListener('hutong:open-collection',openCollection);
 tools.insertBefore(button('背包',()=>{tab(false);void openBag();}),tools.querySelector('#settings-open'));
 const favorites=button('收藏',()=>openCollection());favorites.id='collection-open';tools.insertBefore(favorites,tools.querySelector('#settings-open'));
 tools.insertBefore(button('回看',()=>void journal()),tools.querySelector('#settings-open'));
 async function respond(o:Offer,answer:string){try{await request('offer',{id:o.id,answer,client});signature='';}catch(e){notice((e as Error).message);}}
 function drawOffers(){const pane=root.querySelector<HTMLElement>('#life-offers')!,next=JSON.stringify([bridge.user?.id,offers,Math.floor(Date.now()/1000)]);if(next===signature)return;signature=next;pane.replaceChildren();pane.hidden=!offers.length||!bridge.user;const places:Record<string,string>={rest:'休息室',arcade:'娱乐室',dance:'舞室',gym:'健身房'};for(const o of offers){const incoming=o.recipient===bridge.user?.id;const row=document.createElement('div');row.className='life-offer';const text=document.createElement('p');const seconds=Math.max(0,Math.ceil((o.expires-Date.now()-clockOffset)/1000));const place=places[o.item]||'休息室';text.textContent=o.kind==='gift'?`${incoming?o.fromRole+' 想送给你': '等待 '+o.toRole+' 收下'} ${o.item} · ${seconds} 秒`:o.status==='accepted'?`与 ${incoming?o.fromRole:o.toRole} 相约${place} · ${seconds} 秒`:`${incoming?o.fromRole+' 邀你': '邀请 '+o.toRole} 一起去${place} · ${seconds} 秒`;row.append(text);if(incoming&&o.status==='pending')row.append(button('接受',()=>void respond(o,'accept')),button('婉拒',()=>void respond(o,'reject')));if(!incoming||o.status==='accepted')row.append(button('取消',()=>void respond(o,'cancel')));pane.append(row);}}
 const key=(e:KeyboardEvent)=>{if(bridge.active?.mode==='piano'||e.repeat||document.querySelector('dialog[open]')||/INPUT|TEXTAREA/.test(document.activeElement?.tagName??''))return;if(e.code==='KeyM'){e.preventDefault();document.getElementById('room-open')?.click();}if(e.code==='KeyJ'){e.preventDefault();void journal();}if(e.code==='KeyB'){e.preventDefault();void openBag();}};
 window.addEventListener('keydown',key);const timer=setInterval(drawOffers,1000);
 bridge.game.events.once('destroy',()=>{clearInterval(timer);window.removeEventListener('keydown',key);window.removeEventListener('hutong:open-collection',openCollection);root.remove();});
 return{receive(data:any){if(data.clock)clockOffset=data.clock-Date.now();bag=data.bag??bag;collection=data.collection??collection;offers=data.offers??offers;drawBag();drawOffers();if(bridge.user?.id&&owner!==bridge.user.id){owner=bridge.user.id;if(data.recent?.length)notice('有新经历 · J');}},reset(){owner='';bag=[null,null,null,null];collection=[];offers=[];entries=[];memories.reset();signature='';bagSignature='';journalDialog.close();bagDialog.close();drawBag();drawOffers();}};
}
