import {createMvpServer} from '../server/app.mjs';
import {writeFileSync} from 'node:fs';
const app=createMvpServer({dbPath:':memory:'});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));
const root='http://127.0.0.1:'+app.server.address().port,roles=['suki','sid','jilly','laura','kay','franco','cora','amber'],accounts=[],channels=[],samples=[];
const api=async(path,input,cookie='')=>{const response=await fetch(root+'/api/'+path,{method:input?'POST':'GET',headers:{Cookie:cookie,'Content-Type':'application/json'},body:input?JSON.stringify(input):undefined});if(!response.ok)throw new Error(path+': '+response.status);return{response,data:await response.json()};};
for(const [i,role]of roles.entries()){const result=await api('register',{username:'soak_'+i,password:'test-password-123'});const cookie=result.response.headers.get('set-cookie').split(';')[0];await api('claim',{role},cookie);accounts.push(cookie);for(let n=0;n<4;n++){const abort=new AbortController();const res=await fetch(root+`/api/events?client=${i}-${n}`,{headers:{Cookie:cookie},signal:abort.signal});const reader=res.body.getReader();channels.push(abort);void(async()=>{try{while(!(await reader.read()).done){}}catch{}})();}}
const started=Date.now(),duration=Number(process.env.HUTONG_SOAK_SECONDS||1800)*1000;let updates=0,error=null;
try{while(Date.now()-started<duration){await new Promise(r=>setTimeout(r,100));for(const [i,cookie]of accounts.entries()){const p=app.players.get(app.store.byRole(roles[i]).id);await api('presence',{client:`${i}-0`,scene:p.scene,x:p.x+(updates%2?1:-1),y:p.y,facing:updates%4,moving:true,seat:null,hand:null,revision:0},cookie);}updates++;if(updates%600===0){const sample={seconds:Math.round((Date.now()-started)/1000),rss:process.memoryUsage().rss,heap:process.memoryUsage().heapUsed,players:app.players.size,streams:app.streams.size};samples.push(sample);console.log(JSON.stringify(sample));}}}catch(e){error=e.message;}
const result={seconds:Math.round((Date.now()-started)/1000),updates,players:app.players.size,streams:app.streams.size,error,samples};writeFileSync('output/next-mvp-soak.json',JSON.stringify(result,null,2));channels.forEach(c=>c.abort());app.close();console.log(JSON.stringify(result));process.exit(error?1:0);
