import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {createServer as createViteServer} from 'vite';
import {createMvpServer} from '../server/app.mjs';
const require=createRequire(import.meta.url),{chromium}=require('D:/CodexHome/mcp/node/node_modules/playwright');
const backend=createMvpServer({dbPath:':memory:'});await new Promise(r=>backend.server.listen(0,'127.0.0.1',r));
const vite=await createViteServer({server:{port:5187,strictPort:true,host:'127.0.0.1',proxy:{'/api':{target:'http://127.0.0.1:'+backend.server.address().port,changeOrigin:false}}}});await vite.listen();
const origin='http://127.0.0.1:5187',browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-webgl']});
const errors=[],pages=new Map(),accounts=new Map(),roles=['laura','sid','suki','jilly','kay','franco','cora','amber'];
const api=async(page,path,input)=>{const r=await page.context().request.post(origin+'/api/'+path,{data:input});assert.equal(r.status(),200,await r.text());return r.json();};
async function park(page,role,scene,x,y){const p=backend.players.get(accounts.get(role).id);Object.assign(p,{scene,x,y,seat:null,activity:'walk',moving:false,at:Date.now()-3000});if(page){await page.evaluate(({scene,x,y,role})=>{window.dispatchEvent(new CustomEvent('hutong:navigate',{detail:scene==='hutong'?'culture':scene}));window.__socialPreview.bridge.pendingSpawn={scene,x,y,role,facing:0,seat:null,activity:'walk',moving:false};},{scene,x,y,role});await page.waitForFunction(scene=>window.__socialPreview.getState().room===scene,scene);const client=await page.evaluate(()=>window.__socialPreview.getState().client);await api(page,'control',{client});}}
try{
 await mkdir('output/playwright',{recursive:true});
 for(const role of roles){const context=await browser.newContext({viewport:{width:1100,height:800}}),page=await context.newPage();pages.set(role,page);page.on('pageerror',e=>errors.push(e.message));const result=await api(page,'register',{username:'browser_'+role,password:'browser-password-2026',role});accounts.set(role,result.user);
  if(['laura','sid'].includes(role)){await page.goto(origin);await page.waitForFunction(()=>window.__socialPreview?.getState().connected);}
  else{await page.route('**/acceptance-client',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><title>Realtime client</title>'}));await page.goto(origin+'/acceptance-client');await page.evaluate(role=>{window.events=new EventSource('/api/events?client='+role);},role);}
 }
 await new Promise(r=>setTimeout(r,300));assert.equal(backend.players.size,8);assert.equal(backend.streams.size,8);
 const a=pages.get('laura'),b=pages.get('sid');await park(a,'laura','rest',300,180);await park(b,'sid','rest',330,180);backend.store.hand(accounts.get('laura').id,'咖啡',0);await api(a,'control',{client:await a.evaluate(()=>window.__socialPreview.getState().client)});await a.waitForFunction(()=>window.__socialPreview.getState().user.hand==='咖啡');
 const person=(page,role)=>page.locator('.person-row').filter({hasText:new RegExp('^'+role,'i')});await a.locator('#people-open').click();await person(a,'sid').getByText('赠送',{exact:true}).click();await b.locator('#life-offers').getByText('婉拒',{exact:true}).click();await b.waitForFunction(()=>document.querySelector('#life-offers').hidden);assert.equal(backend.store.byRole('laura').hand,'咖啡');
 await person(a,'sid').getByText('赠送',{exact:true}).click();await b.locator('#life-offers').getByText('接受',{exact:true}).click();await b.waitForFunction(()=>window.__socialPreview.getState().user.hand==='咖啡');assert.equal(backend.store.byRole('laura').hand,null);
 await b.locator('.world').focus();await b.keyboard.press('b');await b.locator('#bag-stow').click();await b.waitForFunction(()=>document.querySelector('#bag-slots').textContent.includes('咖啡 × 1'));await b.locator('#bag-slots button').first().click();await b.waitForFunction(()=>document.querySelector('#bag-hand').textContent.includes('咖啡'));await b.locator('#bag-consume').click();await b.waitForFunction(()=>document.querySelector('#bag-hand').textContent==='手里：空');await b.locator('#bag-dialog [data-close-life]').click();
 await park(b,'sid','hutong',192,194);await person(a,'sid').getByText('一起休息',{exact:true}).click();await b.locator('#life-offers').getByText('接受',{exact:true}).click();await a.waitForFunction(()=>document.querySelector('#life-offers').textContent.includes('相约休息室'));await park(b,'sid','rest',320,190);await a.waitForFunction(()=>document.querySelector('#life-offers').hidden);
 await b.locator('.world').focus();await b.keyboard.press('j');await b.waitForFunction(()=>document.querySelector('#memory-caption').textContent.includes('碰面了')&&document.querySelector('#memory-canvas').dataset.ready==='true');assert.ok(Number(await b.locator('#memory-canvas').getAttribute('data-actors'))>=2);await b.locator('#memory-next').click();await b.waitForFunction(()=>document.querySelector('#memory-canvas').dataset.ready==='true');await b.keyboard.press('ArrowLeft');await b.waitForFunction(()=>document.querySelector('#memory-caption').textContent.includes('碰面了')&&document.querySelector('#memory-canvas').dataset.ready==='true');assert.equal(await b.locator('#journal-dialog').getByText('删除',{exact:true}).count(),0);assert.equal(await b.locator('#profile-dialog').count(),0);await b.screenshot({path:'output/playwright/parallel-journal.png'});await b.locator('#journal-dialog [data-close-life]').click();
 await b.reload();await b.waitForFunction(()=>window.__socialPreview?.getState().connected&&window.__socialPreview.getState().room==='rest');await b.waitForFunction(()=>Math.abs(window.__socialPreview.bridge.state().x-320)<3);await b.screenshot({path:'output/playwright/parallel-restored.png'});
 assert.deepEqual(errors,[]);const result={accounts:8,streams:8,giftAccept:true,giftReject:true,bag:true,consumption:true,meeting:true,readOnlyJournal:true,visualMemories:true,restoreRoom:true,errors};await writeFile('output/parallel-browser-acceptance.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}finally{await browser.close();await vite.close();backend.close();}
